### ISSUE TITLE
询问set部分

### ISSUE THREAD

**Issue by yuanyihan** [jiacheng-ye/kg_one2set#3]
SetGenerator文件，好像是没有使用beam的，只是实现了_, tokens = decoder_dist.max(-1)，请问，有什么理由么？

**Comment by jiacheng-ye** [comment]
我在实验时one2seq和one2set都没有用beam search，用了beam search数量会比较多，不能实现数量可控

**Comment by yuanyihan** [comment]
收到，感谢您的回复。我再揣摩一下论文思想。



/*****以下内容是邮件签名自动添加*****/ 
/*****MY_EMAIL_T——邮件尾文件说明开始*****/
#ifndef&nbsp;__MY_EMAIL_T__
#define&nbsp;__MY_EMAIL_T__
#define&nbsp;&nbsp;姓名 &nbsp; &nbsp;"袁一涵" &nbsp;&nbsp;//姓名为袁一涵 
#define&nbsp;&nbsp;QQ号 &nbsp; &nbsp;1226317595&nbsp;//QQ号为1226317595
#define&nbsp;手机号 &nbsp;18192015917&nbsp;//手机号为18192015917
#define&nbsp;E-mail ***@***.***&nbsp;//email
#endif
/*****MY_EMAIL_T——邮件尾文件说明结束*****/
/*********** (C) COPYRIGHT @Yuan Yihan *****END OF FILE****/



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "jiacheng-ye/kg_one2set"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sat, Sep 11, 2021 09:12 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [jiacheng-ye/kg_one2set] 询问set部分 (#3)





 
我在实验时one2seq和one2set都没有用beam search，用了beam search数量会比较多，不能实现数量可控
