### ISSUE TITLE
请教 max_kp_len 和 assign_steps 的区别

### ISSUE THREAD

**Issue by MabelLIng** [jiacheng-ye/kg_one2set#5]
我的理解是：
max_kp_len : 关键词的最大长度
assign_steps：control code 生成的每个关键词长度

那么为什么脚本里 assign_steps < max_kp_len 呢

**Comment by jiacheng-ye** [comment]
你好，你的理解没错。但是assign_steps只在分配目标阶段有用，自回归走两步就能去做目标匹配了，这样也比较高效。max_kp_len是限制了kp的最大长度，目的是方便各个control code下的kp的并行处理，所以准确来说应该是assign_steps <= max_kp_len。
