### ISSUE TITLE
About the result.

### ISSUE THREAD

**Issue by ChainChainC** [jiacheng-ye/kg_one2set#6]
请问提交的sh文件中的各项参数是论文中结果的参数吗？
我最近在尝试复现论文的各项结果，但是提供的one click.sh文件并不能达到预期效果。

以及各个prediction.txt文件是不是就是最终的预测结果输出。

非常期待并感谢您的回答。

**Comment by jiacheng-ye** [comment]
对的 和论文是一样的参数，results_log_5_M_5_M_5_M.txt 里面有多个metric要区分一下
